;; ===Dired Icons===
(use-package nerd-icons-dired
  :after (dired)
  :hook (dired-mode . nerd-icons-dired-mode))

;; ===Dired===
(use-package dired
  :hook
  (dired-mode . dired-hide-details-mode) ; don't show file details by default
  (dired-mode . hl-line-mode) ; Highlight the line the cursor is on
  ;; TODO: create a dired-find-file-dwim for external programs
  :bind ( :map dired-mode-map
          ;; ===Top Row===
          ;; ("1" . )
          ;; ("!" . )
          ;; ("2" . )
          ;; ("@" . )
          ;; ("3" . )
          ;; ("#" . )
          ;; ("4" . )
          ;; ("$" . )
          ;; ("5" . )
          ;; ("%" . )
          ;; ("6" . )
          ;; ("^" . )
          ;; ("7" . )
          ;; ("&" . )
          ;; ("8" . )
          ;; ("*" . )
          ;; ("9" . )
          ;; ("(" . )
          ;; ("0" . )
          ;; (")" . )

          ;; ===2nd Row===
          ;; ("TAB"  . )
          ;; ("BTAB" . )
          ("q" . quit-window)
          ;; ("Q" . )
          ;; ("w" . )
          ;; ("W" . )
          ;; ("e" . )
          ;; ("E" . )
          ("r" . dired-do-rename)
          ("R" . dired-toggle-read-only)
          ("t" . dired-toggle-marks)
          ;; ("T" . )
          ;; ("y" . )
          ;; ("Y" . )
          ("u" . dired-unmark)
          ("U" . dired-unmark-all-marks)
          ("i" . dired-isearch-filenames-regexp)
          ("I" . dired-do-isearch-regexp)
          ;; ("o" . )
          ("O" . dired-do-chown)
          ("p" . dired-previous-line)
          ;; ("P" . )
          ("-" . negative-argument)
          ;; ("_" . )

          ;; ===3rd Row===
          ("<escape>" . keyboard-quit)
          ;; ("a" . )
          ;; ("A" . )
          ;; ("s" . )
          ;; ("S" . )
          ("d" . dired-do-kill-lines)
          ("D" . dired-do-delete)
          ("f" . find-file)
          ;; ("F" . )
          ("g" . revert-buffer)
          ;; ("G" . )
          ("h" . dired-up-directory)
          ;; ("H" . )
          ("j" . dired-next-line)
          ;; ("J" . )
          ("k" . dired-previous-line)
          ;; ("K" . )
          ("l" . dired-find-file)
          ("L" . dired-find-file-other-window)
          ;; (";" . )
          ;; (":" . )
          ("RET" . dired-find-file)
          ;; ("S-RET" . )

          ;; ===4th Row===
          ("z" . dired-undo)
          ;; ("Z" . )
          ("x" . dired-mark)
          ;; ("X" . )
          ("c" . dired-do-copy)
          ("C" . dired-do-copy-regexp)
          ("v" . dired-find-file-other-window)
          ;; ("V" . )
          ;; ("b" . )
          ;; ("B" . )
          ("n" . dired-next-line)
          ;; ("N" . )
          ("m" . dired-mark-files-regexp)
          ("M" . dired-do-chmod)
          ;; ("," . )
          ;; ("<" . )
          ;; ("." . )
          ;; (">" . )
          ("/" . dired-goto-file)
          ;; ("?" . )
          ;; ("'"  . )
          ;; ("\"" . )
          :map cur/sub-leader-keymap
          ("d" . dired)
          )
  :config
  (setq delete-by-moving-to-trash t)
  (setq dired-recursive-copies t)
  (setq dired-recursive-deletes t)
  (setq dired-listing-switches "-A -G -F -h -l -v --group-directories-first --time-style=long-iso")
  (setq dired-dwim-target t)
  (setq dired-auto-revert-buffer #'dired-directory-changed-p)
  (setq dired-free-space nil)
  (setq dired-make-directory-clickable t)
  (setq dired-mouse-drag-files t))

(provide 'cur-config-dired)
