{ ... }:
{
  imports = [
    ./alacritty.nix
    ./anki.nix
    ./brave.nix
    ./discord.nix
    ./emacs
    ./firefox.nix
    ./flatpak.nix
    ./freetube.nix
    ./imv.nix
    ./keepassxc.nix
    ./keymapp.nix
    ./kid3.nix
    ./libreoffice.nix
    ./mpv.nix
    ./mullvad-browser.nix
    ./mullvad-vpn.nix
    ./obs.nix
    ./qbittorrent.nix
    ./signal.nix
    ./swayimg.nix
    ./thunar.nix
    ./thunderbird.nix
    ./tor-browser.nix
    ./veracrypt.nix
    ./zathura.nix
  ];
}
